import type { Metadata } from 'next'
import './globals.css'
import Header from './Header'

export const metadata: Metadata = {
  title: 'Booking.com clone',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <Header />
      <body>{children}</body>
    </html>
  )
}
